const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const version = packageJson.version;

// Generate version.ts for direct import
const versionContent = `// Auto-generated by scripts/inject-version.js
// Do not edit manually - updated on each release
export const APP_VERSION = '${version}';
`;

const versionPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionPath, versionContent);

console.log(`Version ${version} injected into src/version.ts`);
