const fs = require('fs');
const path = require('path');
const { readNotes } = require('./release-notes-lib');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const version = packageJson.version;

// Generate version.ts for direct import
const versionContent = `// Auto-generated by scripts/inject-version.js
// Do not edit manually - updated on each release
export const APP_VERSION = '${version}';
`;

const versionPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionPath, versionContent);

console.log(`Version ${version} injected into src/version.ts`);

// Generate version.json for runtime version checking.
//
// It carries this release's human notes as well as the version string. useVersionCheck
// already polls this file every five minutes with `cache: 'no-store'`, and the service
// worker already serves it network-first, so the update popup can say what actually
// changed without a second request or a new cache strategy.
//
// The entry is absent whenever this runs outside a release (the `prebuild` hook on any
// working tree, or a build of a commit made before the notes file existed), so an empty
// list is a normal outcome, not an error: UpdatePopup falls back to its generic copy.
const releaseEntry = readNotes().releases.find((entry) => entry.version === version);
if (!releaseEntry) {
  console.log(`No release note recorded for ${version}; version.json will carry an empty list`);
}
const versionJsonContent = JSON.stringify(
  {
    version,
    date: releaseEntry ? releaseEntry.date : null,
    notes: releaseEntry ? releaseEntry.notes : [],
  },
  null,
  2
);
const versionJsonPath = path.join(__dirname, '..', 'public', 'version.json');
fs.writeFileSync(versionJsonPath, versionJsonContent);

console.log(`Version ${version} written to public/version.json`);

// Update service worker cache names with version
const swPath = path.join(__dirname, '..', 'public', 'service-worker.js');
let swContent = fs.readFileSync(swPath, 'utf8');

// Replace cache version strings.
// Only the three caches below are versioned. Do NOT add IMAGE_CACHE here: versioning it
// would delete every cached card image on each release (activate() drops any cache whose
// name it doesn't recognise), so players would re-download their art several times a week
// — exactly the Cloudinary bandwidth this cache exists to avoid.
swContent = swContent.replace(
  /const CACHE_NAME = 'when-v[^']+';/,
  `const CACHE_NAME = 'when-v${version}';`
);
swContent = swContent.replace(
  /const STATIC_CACHE = 'when-static-v[^']+';/,
  `const STATIC_CACHE = 'when-static-v${version}';`
);
swContent = swContent.replace(
  /const DYNAMIC_CACHE = 'when-dynamic-v[^']+';/,
  `const DYNAMIC_CACHE = 'when-dynamic-v${version}';`
);

fs.writeFileSync(swPath, swContent);

console.log(`Service worker cache updated to v${version}`);

// Update iOS Xcode project MARKETING_VERSION
const pbxprojPath = path.join(__dirname, '..', 'ios', 'App', 'App.xcodeproj', 'project.pbxproj');
if (fs.existsSync(pbxprojPath)) {
  let pbxContent = fs.readFileSync(pbxprojPath, 'utf8');
  pbxContent = pbxContent.replace(
    /MARKETING_VERSION = [^;]+;/g,
    `MARKETING_VERSION = ${version};`
  );
  fs.writeFileSync(pbxprojPath, pbxContent);
  console.log(`iOS MARKETING_VERSION updated to ${version}`);
} else {
  console.log('iOS project not found, skipping MARKETING_VERSION update');
}
