const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const version = packageJson.version;

// Generate version.ts for direct import
const versionContent = `// Auto-generated by scripts/inject-version.js
// Do not edit manually - updated on each release
export const APP_VERSION = '${version}';
`;

const versionPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionPath, versionContent);

console.log(`Version ${version} injected into src/version.ts`);

// Update service worker cache names with version
const swPath = path.join(__dirname, '..', 'public', 'service-worker.js');
let swContent = fs.readFileSync(swPath, 'utf8');

// Replace cache version strings
swContent = swContent.replace(
  /const CACHE_NAME = 'when-v[^']+';/,
  `const CACHE_NAME = 'when-v${version}';`
);
swContent = swContent.replace(
  /const STATIC_CACHE = 'when-static-v[^']+';/,
  `const STATIC_CACHE = 'when-static-v${version}';`
);
swContent = swContent.replace(
  /const DYNAMIC_CACHE = 'when-dynamic-v[^']+';/,
  `const DYNAMIC_CACHE = 'when-dynamic-v${version}';`
);

fs.writeFileSync(swPath, swContent);

console.log(`Service worker cache updated to v${version}`);
