/**
 * Words that point at a place without being its tag: other names for a country ("USA",
 * "Burma"), demonyms ("German"), and historical polities and regions ("Ottoman", "Gaul").
 * Each maps to the tags that would satisfy it; a mention is satisfied by any one of them.
 *
 * Two consumers, both advisory:
 *
 * - `region-spec.js` uses an alias that maps to exactly one tag as a "did you mean" hint when
 *   a writer puts "USA" where "United States" belongs. It never rewrites the entry; the
 *   writer fixes it, so the map on disk stays what was actually decided.
 * - `region-audit.js` scans a card's own text for these words (and for every taxonomy name)
 *   and lists cards whose tags satisfy none of them. That list is for a human to read, not a
 *   gate: text names places in passing all the time.
 *
 * The polity entries follow the seat-at-the-time rule in docs/regions/tagging-spec.md, so the
 * audit and the spec agree: "Byzantine" is satisfied by Turkey because Constantinople was the
 * seat. Keys are matched case-sensitively on word boundaries, longest first, which is what keeps
 * "turkey" the bird and "china" the porcelain out of it, and lets "Holy Roman Empire" win
 * over "Roman". Keep it plain CommonJS with no dependencies.
 */

const EU = 'Europe';
const MENA = 'Middle East & North Africa';
const SSA = 'Sub-Saharan Africa';
const NA = 'North America';
const SA = 'South America';

/** Alternative names and spellings of a present-day country or region. */
const NAMES = {
  USA: ['United States'],
  US: ['United States'],
  'U.S.': ['United States'],
  America: ['United States'],
  'United States of America': ['United States'],
  UK: ['United Kingdom'],
  Britain: ['United Kingdom'],
  'Great Britain': ['United Kingdom'],
  England: ['United Kingdom'],
  Scotland: ['United Kingdom'],
  Wales: ['United Kingdom'],
  'Northern Ireland': ['United Kingdom'],
  London: ['United Kingdom'],
  Holland: ['Netherlands'],
  'The Netherlands': ['Netherlands'],
  'Czech Republic': ['Czechia'],
  Türkiye: ['Turkey'],
  Turkiye: ['Turkey'],
  Burma: ['Myanmar'],
  Siam: ['Thailand'],
  Ceylon: ['Sri Lanka'],
  Persia: ['Iran'],
  Abyssinia: ['Ethiopia'],
  Zaire: ['Democratic Republic of the Congo'],
  'DR Congo': ['Democratic Republic of the Congo'],
  DRC: ['Democratic Republic of the Congo'],
  Congo: ['Democratic Republic of the Congo', 'Republic of the Congo'],
  "Côte d'Ivoire": ['Ivory Coast'],
  "Cote d'Ivoire": ['Ivory Coast'],
  'Timor-Leste': ['East Timor'],
  'Cabo Verde': ['Cape Verde'],
  Swaziland: ['Eswatini'],
  'São Tomé and Príncipe': ['Sao Tome and Principe'],
  Vatican: ['Vatican City'],
  'Holy See': ['Vatican City'],
  Macao: ['Macau'],
  Korea: ['North Korea', 'South Korea'],
  // Taxonomy names that also name something else. The audit lets these win over the plain name.
  Georgia: ['Georgia', 'United States'],
  Jordan: ['Jordan', 'Israel', 'Palestine'],
  Niger: ['Niger', 'Mali', 'Nigeria'],
  'Republic of Korea': ['South Korea'],
  'Soviet Union': ['Russia'],
  USSR: ['Russia'],
  Hawaii: ['United States'],
  'New England': ['United States'],
  'New Mexico': ['United States'],
  'New South Wales': ['Australia'],
  Alaska: ['United States'],
  Siberia: ['Russia'],
  Tibet: ['China'],
  Manchuria: ['China'],
  Kashmir: ['India', 'Pakistan'],
  Punjab: ['India', 'Pakistan'],
  Bengal: ['India', 'Bangladesh'],
  Corsica: ['France'],
  Sicily: ['Italy'],
  Sardinia: ['Italy'],
  Crete: ['Greece'],
  Anatolia: ['Turkey'],
  Istanbul: ['Turkey'],
  Constantinople: ['Turkey'],
  Jerusalem: ['Israel', 'Palestine'],
  'Holy Land': ['Israel', 'Palestine', MENA],
  Levant: ['Syria', 'Lebanon', 'Israel', 'Palestine', 'Jordan', MENA],
  Mesopotamia: ['Iraq', 'Syria'],
  Europe: [EU],
  Africa: [SSA, MENA],
  'Middle East': [MENA],
  'North Africa': [MENA],
  'West Indies': [NA],
  Caribbean: [NA],
  'Central America': [NA],
  'Latin America': [NA, SA],
  'East Indies': ['Indonesia'],
};

/** Demonyms and adjectives. */
const DEMONYMS = {
  American: ['United States'],
  'African American': ['United States'],
  'North American': [NA],
  'South American': [SA],
  'Central American': [NA],
  'Latin American': [NA, SA],
  British: ['United Kingdom'],
  English: ['United Kingdom'],
  Scottish: ['United Kingdom'],
  Welsh: ['United Kingdom'],
  Irish: ['Ireland', 'United Kingdom'],
  French: ['France'],
  German: ['Germany'],
  Germanic: ['Germany'],
  Italian: ['Italy'],
  Spanish: ['Spain'],
  Portuguese: ['Portugal'],
  Dutch: ['Netherlands'],
  Belgian: ['Belgium'],
  Swiss: ['Switzerland'],
  Austrian: ['Austria'],
  Hungarian: ['Hungary'],
  Czech: ['Czechia'],
  Polish: ['Poland'],
  Russian: ['Russia'],
  Soviet: ['Russia'],
  Ukrainian: ['Ukraine'],
  Swedish: ['Sweden'],
  Norwegian: ['Norway'],
  Danish: ['Denmark'],
  Finnish: ['Finland'],
  Icelandic: ['Iceland'],
  Greek: ['Greece'],
  Serbian: ['Serbia'],
  Croatian: ['Croatia'],
  Romanian: ['Romania'],
  Bulgarian: ['Bulgaria'],
  Turkish: ['Turkey'],
  Egyptian: ['Egypt'],
  Persian: ['Iran'],
  Iranian: ['Iran'],
  Iraqi: ['Iraq'],
  Syrian: ['Syria'],
  Israeli: ['Israel'],
  Palestinian: ['Palestine'],
  Saudi: ['Saudi Arabia'],
  Arab: [MENA],
  Arabian: ['Saudi Arabia', MENA],
  Afghan: ['Afghanistan'],
  Pakistani: ['Pakistan'],
  Indian: ['India'],
  Chinese: ['China'],
  Japanese: ['Japan'],
  Korean: ['North Korea', 'South Korea'],
  Mongol: ['Mongolia'],
  Mongolian: ['Mongolia'],
  Vietnamese: ['Vietnam'],
  Thai: ['Thailand'],
  Indonesian: ['Indonesia'],
  Filipino: ['Philippines'],
  Canadian: ['Canada'],
  Mexican: ['Mexico'],
  Cuban: ['Cuba'],
  Haitian: ['Haiti'],
  Brazilian: ['Brazil'],
  Argentine: ['Argentina'],
  Argentinian: ['Argentina'],
  Chilean: ['Chile'],
  Peruvian: ['Peru'],
  Colombian: ['Colombia'],
  Venezuelan: ['Venezuela'],
  Australian: ['Australia'],
  Ethiopian: ['Ethiopia'],
  Nigerian: ['Nigeria'],
  Kenyan: ['Kenya'],
  Ghanaian: ['Ghana'],
  Moroccan: ['Morocco'],
  Algerian: ['Algeria'],
  European: [EU],
  African: [SSA, MENA],
};

/** Historical polities, peoples and places, mapped by the seat-at-the-time rule. */
const HISTORICAL = {
  Roman: ['Italy'],
  Rome: ['Italy'],
  Byzantine: ['Turkey'],
  'Eastern Roman': ['Turkey'],
  'Golden Horde': ['Russia'],
  Byzantium: ['Turkey'],
  Ottoman: ['Turkey'],
  Ottomans: ['Turkey'],
  Venetian: ['Italy'],
  Venice: ['Italy'],
  Florentine: ['Italy'],
  Genoese: ['Italy'],
  Athenian: ['Greece'],
  Athens: ['Greece'],
  Spartan: ['Greece'],
  Sparta: ['Greece'],
  Macedonian: ['Greece', 'North Macedonia'],
  Prussia: ['Germany', 'Poland', 'Russia'],
  Prussian: ['Germany', 'Poland', 'Russia'],
  Frankish: ['France', 'Germany'],
  Franks: ['France', 'Germany'],
  Gaul: ['France'],
  Gallic: ['France'],
  Hispania: ['Spain', 'Portugal'],
  Britannia: ['United Kingdom'],
  Viking: ['Norway', 'Denmark', 'Sweden', 'Iceland'],
  Vikings: ['Norway', 'Denmark', 'Sweden', 'Iceland'],
  Norse: ['Norway', 'Denmark', 'Sweden', 'Iceland'],
  Moorish: ['Morocco', 'Spain'],
  Moors: ['Morocco', 'Spain'],
  Carthage: ['Tunisia'],
  Carthaginian: ['Tunisia'],
  Phoenician: ['Lebanon'],
  Babylon: ['Iraq'],
  Babylonian: ['Iraq'],
  Assyrian: ['Iraq'],
  Sumerian: ['Iraq'],
  Hittite: ['Turkey'],
  Achaemenid: ['Iran'],
  Parthian: ['Iran'],
  Sasanian: ['Iran'],
  Abbasid: ['Iraq'],
  Umayyad: ['Syria', 'Spain'],
  Mughal: ['India'],
  Aztec: ['Mexico'],
  Inca: ['Peru'],
  Maya: ['Mexico', 'Guatemala', 'Belize', 'Honduras'],
  Mayan: ['Mexico', 'Guatemala', 'Belize', 'Honduras'],
  'Holy Roman Empire': ['Germany', 'Austria', 'Czechia', 'Italy'],
  Czechoslovakia: ['Czechia', 'Slovakia'],
  Yugoslavia: [
    'Serbia',
    'Croatia',
    'Slovenia',
    'Bosnia and Herzegovina',
    'Montenegro',
    'North Macedonia',
    'Kosovo',
  ],
  Rhodesia: ['Zimbabwe', 'Zambia'],
  'Austria-Hungary': ['Austria', 'Hungary'],
  'Austro-Hungarian': ['Austria', 'Hungary'],
};

/**
 * Phrases that contain an alias but name something else. Removed from the text before
 * matching, so "Indian Ocean" does not read as a mention of India.
 */
const STOP_PHRASES = [
  'Indian Ocean',
  'American Indian',
  'Native American',
  'Native Americans',
  'Roman Catholic',
  'Greek fire',
  'German measles',
  'Spanish flu',
  'Spanish Flu',
  'Hong Kong flu',
  'Hong Kong Flu',
  'Asian flu',
  'Arabic numerals',
];

const ALIASES = { ...NAMES, ...DEMONYMS, ...HISTORICAL };

module.exports = { ALIASES, NAMES, DEMONYMS, HISTORICAL, STOP_PHRASES };
